Update types.go, add Delete field to struct BundleSpec
AutomationBroker/broker-client-go pull request #10
Opened 2018-07-11 17:10 UTC by alaypatel07

2018-07-11 18:26 UTC, jmrodri commented on pkg/apis/automationbroker/v1alpha1/types.go
> +	Delete bool   `json:delete`
should be
```
`json:"delete"`
```

2018-07-11 18:27 UTC, jmrodri requested changes
add quotes to delete

2018-07-13 19:02 UTC, shawn-hurley approved these changes

2018-07-13 19:11 UTC, eriknelson approved these changes

2018-07-13 19:12 UTC, merged